[context.production.environment]
    VITE_API_URL = "https://api-dev.fitbout.io"

[context.deploy-preview.environment]
    VITE_API_URL = ""

[[redirects]]
    from = "/api/*"
    to = "https://api-dev.fitbout.io/api/:splat"
    status = 200
    force = true
    [redirects.headers]
        X-Impersonate-User = "1"

[[redirects]]
    from = "*"
    to = "/index.html"
    status = 200